### ISSUE TITLE
consider adding image to readme of the initial image and photo of what cnc machine produced

### ISSUE THREAD

**Issue by matkoniecz** [AbhyudayaSharma/image2gcode#2]

**Comment by AbhyudayaSharma** [comment]
Is that a request to add the screenshot of the produced GCode to the Readme?
Could you please do that so that I can verify that it is running fine on someone else's computer?

**Comment by AbhyudayaSharma** [comment]
![screenshot_20181208_092543](https://user-images.githubusercontent.com/11471599/49681638-61becf00-facb-11e8-8e74-5bf28e096830.png)
![line_simpleline](https://user-images.githubusercontent.com/11471599/49681640-67b4b000-facb-11e8-8206-48be8ee7f108.png)
Please find the generated GCode for the simple image.
